version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - /Users/jay/Documents/tools/mongo/data:/data/db
    # networks:
    #   - backend
    #   - frontend
    # depends-on:
    #   - db
