version: '3.1'

services:
  zk:
    image: zookeeper:latest
    restart: always
    hostname: zk
    container_name: zk
    # environment:
    ports:
      - "2181:2181"
    volumes:
      - /Users/jay/Documents/tools/zk-kafka/zk/data:/data
      - /Users/jay/Documents/tools/zk-kafka/zk/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zk:2888:3888

  kafka:
    image: wurstmeister/kafka:2.10-0.8.2.2
    restart: always
    hostname: kafka
    container_name: kafka
    # environment:
    ports:
      - "9092:9092"
    volumes:
      - /Users/jay/Documents/tools/zk-kafka/kafka/logs:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://:9092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zk
